intermediate save linux build_libs refactor

diff --git a/scripts/linux/build_aac b/scripts/linux/build_aac
--- a/scripts/linux/build_aac
+++ b/scripts/linux/build_aac
@@ -1,9 +1,23 @@
 #!/usr/bin/bash
 
-cd $HOME/ffmpeg_sources && \
-git -C fdk-aac pull 2> /dev/null || git clone --depth 1 https://github.com/mstorsjo/fdk-aac && \
-cd fdk-aac && \
-autoreconf -fiv && \
-./configure --prefix="$HOME/ffmpeg_build" --enable-shared && \
-make -j$(nproc) && \
-make install
+#SOURCE_DIR=$HOME/ffmpeg_sources
+#BUILD_DIR=$HOME/ffmpeg_build
+
+if [[ ! -f "$BUILD_DIR/lib/libfdk-aac.so" ]]; then
+    cd $SOURCE_DIR
+    if [ ! -d fdk-aac ]; then
+        git -C fdk-aac pull 2> /dev/null || git clone --depth 1 https://github.com/mstorsjo/fdk-aac
+    fi
+    cd fdk-aac
+    autoreconf -fiv
+    ./configure --prefix="$BUILD_DIR" --enable-shared
+    make -j$(nproc)
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "AAC compilation failed"
+        exit 1
+    fi
+    make install
+else
+    echo "Found existing AAC build $BUILD_DIR/lib/libfdk-aac.so"
+fi
diff --git a/scripts/linux/build_automake b/scripts/linux/build_automake
--- a/scripts/linux/build_automake
+++ b/scripts/linux/build_automake
@@ -1,15 +1,35 @@
 #!/usr/bin/bash
 
-sudo apt install -y autoconf make wget g++ && \
-sudo apt remove -y automake && \
-mkdir -p $HOME/sources && cd ~/sources && \
-if [ ! -d "automake-1.17" ]; then
-    wget https://ftp.gnu.org/gnu/automake/automake-1.17.tar.gz &&\
-    tar -xzf automake-1.17.tar.gz
-fi && \
-cd automake-1.17 && \
-./configure && \
-make && \
-sudo make install && \
-export ACLOCAL_PATH=/usr/share/aclocal && \
-automake --version
+#SOURCE_DIR=$HOME/ffmpeg_sources
+#BUILD_DIR=$HOME/ffmpeg_build
+#BIN_DIR=$HOME/bin
+
+if [[ ! -f "/usr/local/bin/automake-1.17" ]]; then
+    sudo apt install -y autoconf
+    sudo apt remove -y automake
+    cd $SOURCE_DIR
+    if [ ! -f "automake-1.17.tar.gz" ]; then
+        wget https://ftp.gnu.org/gnu/automake/automake-1.17.tar.gz
+    fi
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "automake download failed"
+        exit 1
+    fi
+    if [ ! -d "automake-1.17" ]; then
+        tar -xzf automake-1.17.tar.gz
+    fi
+    cd automake-1.17
+    ./configure
+    make
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "automake compliation failed"
+        exit 1
+    fi
+    sudo make install
+    export ACLOCAL_PATH=/usr/share/aclocal
+    automake --version
+else
+    echo "Found existing automake installation /usr/local/bin/automake-1.17"
+fi
diff --git a/scripts/linux/build_libxml2 b/scripts/linux/build_libxml2
--- a/scripts/linux/build_libxml2
+++ b/scripts/linux/build_libxml2
@@ -1,9 +1,21 @@
 #!/usr/bin/bash
 
-mkdir -p $HOME/libxml2_sources && \
-cd $HOME/libxml2_sources && \
-git -C libxml2 pull 2> /dev/null || git clone --depth 1 https://github.com/GNOME/libxml2.git && \
-cd libxml2 && \
-./autogen.sh  --prefix=$HOME/libxml2_build --without-python && \
-make -j$(nproc) && \
-make install
+#SOURCE_DIR=$HOME/ffmpeg_sources
+#BUILD_DIR=$HOME/ffmpeg_build
+#BIN_DIR=$HOME/bin
+
+if [[ ! -f "$BUILD_DIR/lib/libxml2.so" ]]; then
+    cd $SOURCE_DIR
+    git -C libxml2 pull 2> /dev/null || git clone --depth 1 https://github.com/GNOME/libxml2.git
+    cd libxml2
+    ./autogen.sh  --prefix=$BUILD_DIR --without-python
+    make -j$(nproc)
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "libxml2 compilation failed"
+        exit 1
+    fi
+    make install
+else
+    echo "Found existing libxml2 installation"
+fi
diff --git a/scripts/linux/build_nasm b/scripts/linux/build_nasm
--- a/scripts/linux/build_nasm
+++ b/scripts/linux/build_nasm
@@ -1,12 +1,33 @@
 #!/usr/bin/bash
 
-cd $HOME/ffmpeg_sources && \
-if [[ ! -d "nasm-2.16.01" ]]; then
-    wget https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.bz2 && \
-    tar xjvf nasm-2.16.01.tar.bz2
-fi && \
-cd nasm-2.16.01 && \
-./autogen.sh && \
-PATH="$HOME/bin:$PATH" ./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" && \
-make -j$(nproc) && \
-make install
+#SOURCE_DIR=$HOME/ffmpeg_sources
+#BUILD_DIR=$HOME/ffmpeg_build
+#BIN_DIR=$HOME/bin
+
+if [[ ! -f "$BIN_DIR/nasm" ]]; then
+
+    cd $SOURCE_DIR
+    if [ ! -f nasm-2.16.01.tar.bz2 ]; then
+        wget https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.bz2
+    fi
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "NASM download failed"
+        exit 1
+    fi
+    if [[ ! -d "nasm-2.16.01" ]]; then
+        tar xjvf nasm-2.16.01.tar.bz2
+    fi
+    cd nasm-2.16.01
+    ./autogen.sh
+    PATH="$BIN_DIR:$PATH" ./configure --prefix="$BUILD_DIR" --bindir="$BIN_DIR"
+    make -j$(nproc)
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "NASM compilation failed"
+        exit 1
+    fi
+    make install
+else
+    echo "Found existing NASM installation: $BIN_DIR/nasm"
+fi
diff --git a/scripts/linux/build_sdl2 b/scripts/linux/build_sdl2
--- a/scripts/linux/build_sdl2
+++ b/scripts/linux/build_sdl2
@@ -1,11 +1,31 @@
 #!/usr/bin/bash
 
-cd $HOME/ffmpeg_sources && \
-if [ ! -d "SDL-release-2.32.0" ]; then
-    wget -O release-2.32.0.tar.gz https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.32.0.tar.gz && \
-    tar xzvf release-2.32.0.tar.gz
-fi && \
-cd SDL-release-2.32.0 && \
-./configure --prefix=$HOME/ffmpeg_build && \
-make -j$(nproc) && \
-make install
+#SOURCE_DIR=$HOME/ffmpeg_sources
+#BUILD_DIR=$HOME/ffmpeg_build
+#BIN_DIR=$HOME/bin
+
+if [[ ! -f "$BUILD_DIR/lib/libSDL2.so" ]]; then
+    cd $SOURCE_DIR
+    if [ ! -f release-2.32.0.tar.gz ]; then
+        wget -O release-2.32.0.tar.gz https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.32.0.tar.gz
+    fi
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "SDL2 download failed"
+        exit 1
+    fi
+    if [ ! -d "SDL-release-2.32.0" ]; then
+        tar xzvf release-2.32.0.tar.gz
+    fi
+    cd SDL-release-2.32.0
+    ./configure --prefix=$BUILD_DIR
+    make -j$(nproc)
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "SDL2 compilation failed"
+        exi 1
+    fi
+    make install
+else
+    echo "Found existing SDL2 installation $BUILD_DIR/lib/libSDL2.so"
+fi
