mac scripts for portable libraries

diff --git a/scripts/mac/build_aac b/scripts/mac/build_aac
--- a/scripts/mac/build_aac
+++ b/scripts/mac/build_aac
@@ -1,9 +1,19 @@
 #!/bin/bash
-
-cd $HOME/ffmpeg_sources && \
-git -C fdk-aac pull 2> /dev/null || git clone --depth 1 https://github.com/mstorsjo/fdk-aac && \
-cd fdk-aac && \
-autoreconf -fiv && \
-./configure --prefix="$HOME/ffmpeg_build" --enable-shared && \
-make -j$(nproc) && \
-make install
+BASE=$PWD
+if [ ! -f "$BUILD_DIR/lib/libfdk-aac.dylib" ]; then
+    cd $SOURCE_DIR
+    git -C fdk-aac pull 2> /dev/null || git clone --depth 1 https://github.com/mstorsjo/fdk-aac
+    cd fdk-aac
+    autoreconf -fiv
+    ./configure --prefix="$BUILD_DIR" --enable-shared
+    make -j$(nproc)
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "aac compilation failed"
+        exit 1
+    fi
+    make install
+else
+    echo "Found existing aac library at $BUILD_DIR/lib/libfdk-aac.dylib"
+fi
+cd $BASE
diff --git a/scripts/mac/build_cmake b/scripts/mac/build_cmake
--- a/scripts/mac/build_cmake
+++ b/scripts/mac/build_cmake
@@ -1,16 +1,30 @@
 #!/bin/bash
 
+BASE=$PWD
 FILE="/usr/local/bin/cmake"
 if [ ! -f "$FILE" ]; then
-    cd $HOME/sources && \
+    cd $SOURCE_DIR && \
+    if [ ! -f "cmake-3.20.0.tar.gz" ]; then
+        wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz
+    fi
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "cmake download failed"
+        exit 1
+    fi
     if [ ! -d "cmake-3.20.0" ]; then
-        wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz && \
         tar -zxvf cmake-3.20.0.tar.gz
-    fi && \
-    cd cmake-3.20.0 && \
-    ./bootstrap && \
-    make && \
-    sudo make install && \
-    cmake --version
+    fi
+    cd cmake-3.20.0
+    ./bootstrap
+    make
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "cmake compilation failed"
+        exit 1
+    fi
+    sudo make install
+else
+    echo "Found exsiting cmake installation at $FILE"
 fi
-/usr/local/bin/cmake --version
+cd $BASE
diff --git a/scripts/mac/build_ffmpeg b/scripts/mac/build_ffmpeg
--- a/scripts/mac/build_ffmpeg
+++ b/scripts/mac/build_ffmpeg
@@ -1,26 +1,46 @@
 #!/bin/bash
 
-cd $HOME/ffmpeg_sources && \
-if [[ ! -d "ffmpeg" ]]; then
-  wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
-  tar xjvf ffmpeg-snapshot.tar.bz2
+BASE=$PWD
+
+if [ ! -f "$BUILD_DIR/lib/libavcodec.dylib" ]; then
+    cd $SOURCE_DIR
+    if [ -f "$SOURCE_DIR/ffmpeg-snapshot.tar.bz2" ]; then
+        wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
+    fi
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "ffmpeg download failed"
+        exit 1
+    fi
+    if [[ ! -d "ffmpeg" ]]; then
+        tar xjvf ffmpeg-snapshot.tar.bz2
+    fi
+    cd ffmpeg
+    PATH="$BUILD_DIR/bin:$PATH" PKG_CONFIG_PATH="$BUILD_DIR/lib/pkgconfig" ./configure \
+        --prefix="$BUILD_DIR" \
+        --extra-cflags="-I$BUILD_DIR/include" \
+        --extra-ldflags="-L$BUILD_DIR/lib" \
+        --extra-libs="-lpthread -lm" \
+        --ld="g++" \
+        --bindir="$BUILD_DIR/bin" \
+        --enable-shared \
+        --enable-pic \
+        --disable-static \
+        --enable-gpl \
+        --enable-libfdk-aac \
+        --enable-libx264 \
+        --enable-libx265 \
+        --enable-nonfree && \
+    PATH="$BUILD_DIR/bin:$PATH" make -j$(nproc)
+    make install && \
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "ffmpeg download failed"
+        exit 1
+    fi
+    hash -r
+else
+    echo "Found existing ffmpeg libraries at $BUILD_DIR/lib"
 fi
-cd ffmpeg && \
-PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
-  --prefix="$HOME/ffmpeg_build" \
-  --extra-cflags="-I$HOME/ffmpeg_build/include" \
-  --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
-  --extra-libs="-lpthread -lm" \
-  --ld="g++" \
-  --bindir="$HOME/bin" \
-  --enable-shared \
-  --enable-pic \
-  --disable-static \
-  --enable-gpl \
-  --enable-libfdk-aac \
-  --enable-libx264 \
-  --enable-libx265 \
-  --enable-nonfree && \
-PATH="$HOME/bin:$PATH" make -j$(nproc) && \
-make install && \
-hash -r
+
+cd $BASE
diff --git a/scripts/mac/build_sdl2 b/scripts/mac/build_sdl2
--- a/scripts/mac/build_sdl2
+++ b/scripts/mac/build_sdl2
@@ -1,11 +1,30 @@
 #!/bin/bash
 
-cd $HOME/ffmpeg_sources && \
-if [ ! -d "SDL-release-2.32.0" ]; then
-    wget -O release-2.32.0.tar.gz https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.32.0.tar.gz && \
-    tar xzvf release-2.32.0.tar.gz
-fi && \
-cd SDL-release-2.32.0 && \
-./configure --prefix=$HOME/ffmpeg_build && \
-make -j$(nproc) && \
-make install
+BASE=$PWD
+
+if [ ! -f "$BUILD_DIR/lib/libSDL2.dylib" ]; then
+    cd $SOURCE_DIR
+    if [ ! -f release-2.32.0.tar.gz ]; then
+        wget -O release-2.32.0.tar.gz https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.32.0.tar.gz
+    fi
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "sdl2 download failed"
+        exit 1
+    fi
+    if [ ! -d "SDL-release-2.32.0" ]; then
+        tar xzvf release-2.32.0.tar.gz
+    fi
+    cd SDL-release-2.32.0
+    ./configure --prefix=$BUILD_DIR
+    make -j$(nproc)
+    if [ $result -ne 0 ]; then
+        echo "sdl2 compilation failed"
+        exit 1
+    fi
+    make install
+else
+    echo "Found existing sdl2 library at $BUILD_DIR/lib/libSDL2.dylib"
+fi
+
+cd $BASE
